// Generated by gencpp from file kari_dronecop_rd_payload_mgmt/bboxes_comp_status.msg
// DO NOT EDIT!


#ifndef KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_BBOXES_COMP_STATUS_H
#define KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_BBOXES_COMP_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <kari_dronecop_rd_payload_mgmt/bbox.h>

namespace kari_dronecop_rd_payload_mgmt
{
template <class ContainerAllocator>
struct bboxes_comp_status_
{
  typedef bboxes_comp_status_<ContainerAllocator> Type;

  bboxes_comp_status_()
    : header()
    , img_ros_src()
    , img_ros_res()
    , bboxes()  {
    }
  bboxes_comp_status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , img_ros_src(_alloc)
    , img_ros_res(_alloc)
    , bboxes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_ros_src_type;
  _img_ros_src_type img_ros_src;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_ros_res_type;
  _img_ros_res_type img_ros_res;

   typedef std::vector< ::kari_dronecop_rd_payload_mgmt::bbox_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::kari_dronecop_rd_payload_mgmt::bbox_<ContainerAllocator> >> _bboxes_type;
  _bboxes_type bboxes;





  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> const> ConstPtr;

}; // struct bboxes_comp_status_

typedef ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<std::allocator<void> > bboxes_comp_status;

typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status > bboxes_comp_statusPtr;
typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status const> bboxes_comp_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.img_ros_src == rhs.img_ros_src &&
    lhs.img_ros_res == rhs.img_ros_res &&
    lhs.bboxes == rhs.bboxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kari_dronecop_rd_payload_mgmt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb201f4f97cdc4d322d2918c40138f18";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb201f4f97cdc4d3ULL;
  static const uint64_t static_value2 = 0x22d2918c40138f18ULL;
};

template<class ContainerAllocator>
struct DataType< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kari_dronecop_rd_payload_mgmt/bboxes_comp_status";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"sensor_msgs/Image img_ros_src\n"
"sensor_msgs/Image img_ros_res\n"
"bbox[] bboxes\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: kari_dronecop_rd_payload_mgmt/bbox\n"
"float64 probability\n"
"int64 xmin\n"
"int64 ymin\n"
"int64 xmax\n"
"int64 ymax\n"
"int16 class_id\n"
"int16 track_id\n"
"string class_info\n"
;
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.img_ros_src);
      stream.next(m.img_ros_res);
      stream.next(m.bboxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bboxes_comp_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kari_dronecop_rd_payload_mgmt::bboxes_comp_status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "img_ros_src: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img_ros_src);
    s << indent << "img_ros_res: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img_ros_res);
    s << indent << "bboxes[]" << std::endl;
    for (size_t i = 0; i < v.bboxes.size(); ++i)
    {
      s << indent << "  bboxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::kari_dronecop_rd_payload_mgmt::bbox_<ContainerAllocator> >::stream(s, indent + "    ", v.bboxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_BBOXES_COMP_STATUS_H
