// Generated by gencpp from file kari_dronecop_rd_payload_mgmt/payload_fc_rc_states.msg
// DO NOT EDIT!


#ifndef KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_FC_RC_STATES_H
#define KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_FC_RC_STATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kari_dronecop_rd_payload_mgmt
{
template <class ContainerAllocator>
struct payload_fc_rc_states_
{
  typedef payload_fc_rc_states_<ContainerAllocator> Type;

  payload_fc_rc_states_()
    : header()
    , rcin_rssi(0)
    , rcin_channels()
    , rcout_channels()  {
    }
  payload_fc_rc_states_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rcin_rssi(0)
    , rcin_channels(_alloc)
    , rcout_channels(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _rcin_rssi_type;
  _rcin_rssi_type rcin_rssi;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _rcin_channels_type;
  _rcin_channels_type rcin_channels;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _rcout_channels_type;
  _rcout_channels_type rcout_channels;





  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> const> ConstPtr;

}; // struct payload_fc_rc_states_

typedef ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<std::allocator<void> > payload_fc_rc_states;

typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states > payload_fc_rc_statesPtr;
typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states const> payload_fc_rc_statesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rcin_rssi == rhs.rcin_rssi &&
    lhs.rcin_channels == rhs.rcin_channels &&
    lhs.rcout_channels == rhs.rcout_channels;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kari_dronecop_rd_payload_mgmt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb4f0b20391ab8001ca6707f0641cbcf";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb4f0b20391ab800ULL;
  static const uint64_t static_value2 = 0x1ca6707f0641cbcfULL;
};

template<class ContainerAllocator>
struct DataType< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kari_dronecop_rd_payload_mgmt/payload_fc_rc_states";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Payload TmTc in ROS env., flight control radio control status\n"
"Header header\n"
"uint8 rcin_rssi\n"
"uint16[] rcin_channels\n"
"uint16[] rcout_channels\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rcin_rssi);
      stream.next(m.rcin_channels);
      stream.next(m.rcout_channels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct payload_fc_rc_states_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kari_dronecop_rd_payload_mgmt::payload_fc_rc_states_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rcin_rssi: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rcin_rssi);
    s << indent << "rcin_channels[]" << std::endl;
    for (size_t i = 0; i < v.rcin_channels.size(); ++i)
    {
      s << indent << "  rcin_channels[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.rcin_channels[i]);
    }
    s << indent << "rcout_channels[]" << std::endl;
    for (size_t i = 0; i < v.rcout_channels.size(); ++i)
    {
      s << indent << "  rcout_channels[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.rcout_channels[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_FC_RC_STATES_H
