// Generated by gencpp from file kari_dronecop_rd_payload_mgmt/payload_mc_gimbal_ctrl_cmd.msg
// DO NOT EDIT!


#ifndef KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_MC_GIMBAL_CTRL_CMD_H
#define KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_MC_GIMBAL_CTRL_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kari_dronecop_rd_payload_mgmt
{
template <class ContainerAllocator>
struct payload_mc_gimbal_ctrl_cmd_
{
  typedef payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> Type;

  payload_mc_gimbal_ctrl_cmd_()
    : header()
    , pan_rate_cmd(0.0)
    , tilt_rate_cmd(0.0)
    , zoom_pos_cmd(0.0)
    , img_select_cmd(0)
    , img_capture_cmd(0)
    , homing_mode_cmd(0)
    , netgun_mode_cmd(0)
    , offbd_mode_cmd(0)
    , ub(0.0)
    , vb(0.0)
    , wb(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , xned(0.0)
    , yned(0.0)
    , zned(0.0)
    , vnx(0.0)
    , vny(0.0)
    , vnz(0.0)
    , comp_head(0.0)  {
    }
  payload_mc_gimbal_ctrl_cmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pan_rate_cmd(0.0)
    , tilt_rate_cmd(0.0)
    , zoom_pos_cmd(0.0)
    , img_select_cmd(0)
    , img_capture_cmd(0)
    , homing_mode_cmd(0)
    , netgun_mode_cmd(0)
    , offbd_mode_cmd(0)
    , ub(0.0)
    , vb(0.0)
    , wb(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , xned(0.0)
    , yned(0.0)
    , zned(0.0)
    , vnx(0.0)
    , vny(0.0)
    , vnz(0.0)
    , comp_head(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _pan_rate_cmd_type;
  _pan_rate_cmd_type pan_rate_cmd;

   typedef double _tilt_rate_cmd_type;
  _tilt_rate_cmd_type tilt_rate_cmd;

   typedef double _zoom_pos_cmd_type;
  _zoom_pos_cmd_type zoom_pos_cmd;

   typedef int8_t _img_select_cmd_type;
  _img_select_cmd_type img_select_cmd;

   typedef int8_t _img_capture_cmd_type;
  _img_capture_cmd_type img_capture_cmd;

   typedef int8_t _homing_mode_cmd_type;
  _homing_mode_cmd_type homing_mode_cmd;

   typedef int8_t _netgun_mode_cmd_type;
  _netgun_mode_cmd_type netgun_mode_cmd;

   typedef int8_t _offbd_mode_cmd_type;
  _offbd_mode_cmd_type offbd_mode_cmd;

   typedef float _ub_type;
  _ub_type ub;

   typedef float _vb_type;
  _vb_type vb;

   typedef float _wb_type;
  _wb_type wb;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _xned_type;
  _xned_type xned;

   typedef float _yned_type;
  _yned_type yned;

   typedef float _zned_type;
  _zned_type zned;

   typedef float _vnx_type;
  _vnx_type vnx;

   typedef float _vny_type;
  _vny_type vny;

   typedef float _vnz_type;
  _vnz_type vnz;

   typedef float _comp_head_type;
  _comp_head_type comp_head;





  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct payload_mc_gimbal_ctrl_cmd_

typedef ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<std::allocator<void> > payload_mc_gimbal_ctrl_cmd;

typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd > payload_mc_gimbal_ctrl_cmdPtr;
typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd const> payload_mc_gimbal_ctrl_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pan_rate_cmd == rhs.pan_rate_cmd &&
    lhs.tilt_rate_cmd == rhs.tilt_rate_cmd &&
    lhs.zoom_pos_cmd == rhs.zoom_pos_cmd &&
    lhs.img_select_cmd == rhs.img_select_cmd &&
    lhs.img_capture_cmd == rhs.img_capture_cmd &&
    lhs.homing_mode_cmd == rhs.homing_mode_cmd &&
    lhs.netgun_mode_cmd == rhs.netgun_mode_cmd &&
    lhs.offbd_mode_cmd == rhs.offbd_mode_cmd &&
    lhs.ub == rhs.ub &&
    lhs.vb == rhs.vb &&
    lhs.wb == rhs.wb &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.xned == rhs.xned &&
    lhs.yned == rhs.yned &&
    lhs.zned == rhs.zned &&
    lhs.vnx == rhs.vnx &&
    lhs.vny == rhs.vny &&
    lhs.vnz == rhs.vnz &&
    lhs.comp_head == rhs.comp_head;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kari_dronecop_rd_payload_mgmt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "908374b12b32e1b86be4a9ed12774585";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x908374b12b32e1b8ULL;
  static const uint64_t static_value2 = 0x6be4a9ed12774585ULL;
};

template<class ContainerAllocator>
struct DataType< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kari_dronecop_rd_payload_mgmt/payload_mc_gimbal_ctrl_cmd";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 pan_rate_cmd\n"
"float64 tilt_rate_cmd\n"
"float64 zoom_pos_cmd\n"
"int8 img_select_cmd\n"
"int8 img_capture_cmd\n"
"int8 homing_mode_cmd\n"
"int8 netgun_mode_cmd\n"
"int8 offbd_mode_cmd\n"
"float32 ub\n"
"float32 vb\n"
"float32 wb\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
"float32 xned\n"
"float32 yned\n"
"float32 zned\n"
"float32 vnx\n"
"float32 vny\n"
"float32 vnz\n"
"float32 comp_head\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pan_rate_cmd);
      stream.next(m.tilt_rate_cmd);
      stream.next(m.zoom_pos_cmd);
      stream.next(m.img_select_cmd);
      stream.next(m.img_capture_cmd);
      stream.next(m.homing_mode_cmd);
      stream.next(m.netgun_mode_cmd);
      stream.next(m.offbd_mode_cmd);
      stream.next(m.ub);
      stream.next(m.vb);
      stream.next(m.wb);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.xned);
      stream.next(m.yned);
      stream.next(m.zned);
      stream.next(m.vnx);
      stream.next(m.vny);
      stream.next(m.vnz);
      stream.next(m.comp_head);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct payload_mc_gimbal_ctrl_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kari_dronecop_rd_payload_mgmt::payload_mc_gimbal_ctrl_cmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pan_rate_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.pan_rate_cmd);
    s << indent << "tilt_rate_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.tilt_rate_cmd);
    s << indent << "zoom_pos_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.zoom_pos_cmd);
    s << indent << "img_select_cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.img_select_cmd);
    s << indent << "img_capture_cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.img_capture_cmd);
    s << indent << "homing_mode_cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.homing_mode_cmd);
    s << indent << "netgun_mode_cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.netgun_mode_cmd);
    s << indent << "offbd_mode_cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.offbd_mode_cmd);
    s << indent << "ub: ";
    Printer<float>::stream(s, indent + "  ", v.ub);
    s << indent << "vb: ";
    Printer<float>::stream(s, indent + "  ", v.vb);
    s << indent << "wb: ";
    Printer<float>::stream(s, indent + "  ", v.wb);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "xned: ";
    Printer<float>::stream(s, indent + "  ", v.xned);
    s << indent << "yned: ";
    Printer<float>::stream(s, indent + "  ", v.yned);
    s << indent << "zned: ";
    Printer<float>::stream(s, indent + "  ", v.zned);
    s << indent << "vnx: ";
    Printer<float>::stream(s, indent + "  ", v.vnx);
    s << indent << "vny: ";
    Printer<float>::stream(s, indent + "  ", v.vny);
    s << indent << "vnz: ";
    Printer<float>::stream(s, indent + "  ", v.vnz);
    s << indent << "comp_head: ";
    Printer<float>::stream(s, indent + "  ", v.comp_head);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_MC_GIMBAL_CTRL_CMD_H
