// Generated by gencpp from file kari_dronecop_rd_payload_mgmt/payload_jammer_cmd.msg
// DO NOT EDIT!


#ifndef KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_JAMMER_CMD_H
#define KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_JAMMER_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kari_dronecop_rd_payload_mgmt
{
template <class ContainerAllocator>
struct payload_jammer_cmd_
{
  typedef payload_jammer_cmd_<ContainerAllocator> Type;

  payload_jammer_cmd_()
    : header()
    , f433mhz_band_jmr(0)
    , f900mhz_band_jmr(0)
    , s_band_band_jmr(0)
    , c_band_band_jmr(0)  {
    }
  payload_jammer_cmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , f433mhz_band_jmr(0)
    , f900mhz_band_jmr(0)
    , s_band_band_jmr(0)
    , c_band_band_jmr(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _f433mhz_band_jmr_type;
  _f433mhz_band_jmr_type f433mhz_band_jmr;

   typedef uint8_t _f900mhz_band_jmr_type;
  _f900mhz_band_jmr_type f900mhz_band_jmr;

   typedef uint8_t _s_band_band_jmr_type;
  _s_band_band_jmr_type s_band_band_jmr;

   typedef uint8_t _c_band_band_jmr_type;
  _c_band_band_jmr_type c_band_band_jmr;





  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct payload_jammer_cmd_

typedef ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<std::allocator<void> > payload_jammer_cmd;

typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd > payload_jammer_cmdPtr;
typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd const> payload_jammer_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.f433mhz_band_jmr == rhs.f433mhz_band_jmr &&
    lhs.f900mhz_band_jmr == rhs.f900mhz_band_jmr &&
    lhs.s_band_band_jmr == rhs.s_band_band_jmr &&
    lhs.c_band_band_jmr == rhs.c_band_band_jmr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kari_dronecop_rd_payload_mgmt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19ffd421b190d9c2da04827124829a09";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19ffd421b190d9c2ULL;
  static const uint64_t static_value2 = 0xda04827124829a09ULL;
};

template<class ContainerAllocator>
struct DataType< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kari_dronecop_rd_payload_mgmt/payload_jammer_cmd";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Payload TmTc in ROS env., Jammer, command\n"
"# 433MHz band jamming, control bit no.:0(1: on request, 0: off request)\n"
"# 900MHz band jamming, control bit no.:1(1: on request, 0: off request)\n"
"# 433MHz band jamming, control bit no.:2(1: on request, 0: off request)\n"
"# 433MHz band jamming, control bit no.:3(1: on request, 0: off request)	\n"
"Header header\n"
"uint8 f433mhz_band_jmr\n"
"uint8 f900mhz_band_jmr\n"
"uint8 s_band_band_jmr\n"
"uint8 c_band_band_jmr\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.f433mhz_band_jmr);
      stream.next(m.f900mhz_band_jmr);
      stream.next(m.s_band_band_jmr);
      stream.next(m.c_band_band_jmr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct payload_jammer_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kari_dronecop_rd_payload_mgmt::payload_jammer_cmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "f433mhz_band_jmr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.f433mhz_band_jmr);
    s << indent << "f900mhz_band_jmr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.f900mhz_band_jmr);
    s << indent << "s_band_band_jmr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.s_band_band_jmr);
    s << indent << "c_band_band_jmr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.c_band_band_jmr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_JAMMER_CMD_H
