// Generated by gencpp from file kari_dronecop_rd_payload_mgmt/payload_gcs_heartbeat.msg
// DO NOT EDIT!


#ifndef KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_GCS_HEARTBEAT_H
#define KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_GCS_HEARTBEAT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kari_dronecop_rd_payload_mgmt
{
template <class ContainerAllocator>
struct payload_gcs_heartbeat_
{
  typedef payload_gcs_heartbeat_<ContainerAllocator> Type;

  payload_gcs_heartbeat_()
    : header()
    , ping(0)
    , custom_mode(0)
    , type(0)
    , autopilot(0)
    , base_mode(0)
    , system_status(0)
    , mavlink_version(0)  {
    }
  payload_gcs_heartbeat_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ping(0)
    , custom_mode(0)
    , type(0)
    , autopilot(0)
    , base_mode(0)
    , system_status(0)
    , mavlink_version(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _ping_type;
  _ping_type ping;

   typedef uint32_t _custom_mode_type;
  _custom_mode_type custom_mode;

   typedef uint8_t _type_type;
  _type_type type;

   typedef uint8_t _autopilot_type;
  _autopilot_type autopilot;

   typedef uint8_t _base_mode_type;
  _base_mode_type base_mode;

   typedef uint8_t _system_status_type;
  _system_status_type system_status;

   typedef uint8_t _mavlink_version_type;
  _mavlink_version_type mavlink_version;





  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> const> ConstPtr;

}; // struct payload_gcs_heartbeat_

typedef ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<std::allocator<void> > payload_gcs_heartbeat;

typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat > payload_gcs_heartbeatPtr;
typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat const> payload_gcs_heartbeatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ping == rhs.ping &&
    lhs.custom_mode == rhs.custom_mode &&
    lhs.type == rhs.type &&
    lhs.autopilot == rhs.autopilot &&
    lhs.base_mode == rhs.base_mode &&
    lhs.system_status == rhs.system_status &&
    lhs.mavlink_version == rhs.mavlink_version;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kari_dronecop_rd_payload_mgmt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05113b2cf4c123ad694d8acf2c3a952a";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05113b2cf4c123adULL;
  static const uint64_t static_value2 = 0x694d8acf2c3a952aULL;
};

template<class ContainerAllocator>
struct DataType< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kari_dronecop_rd_payload_mgmt/payload_gcs_heartbeat";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# GCS pinger\n"
"Header header\n"
"uint8 ping\n"
"uint32 custom_mode \n"
"uint8 type\n"
"uint8 autopilot\n"
"uint8 base_mode\n"
"uint8 system_status\n"
"uint8 mavlink_version\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ping);
      stream.next(m.custom_mode);
      stream.next(m.type);
      stream.next(m.autopilot);
      stream.next(m.base_mode);
      stream.next(m.system_status);
      stream.next(m.mavlink_version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct payload_gcs_heartbeat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kari_dronecop_rd_payload_mgmt::payload_gcs_heartbeat_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ping: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ping);
    s << indent << "custom_mode: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.custom_mode);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "autopilot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.autopilot);
    s << indent << "base_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.base_mode);
    s << indent << "system_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.system_status);
    s << indent << "mavlink_version: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mavlink_version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_GCS_HEARTBEAT_H
