// Generated by gencpp from file kari_dronecop_rd_payload_mgmt/payload_fc_vfr_hud_status.msg
// DO NOT EDIT!


#ifndef KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_FC_VFR_HUD_STATUS_H
#define KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_FC_VFR_HUD_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kari_dronecop_rd_payload_mgmt
{
template <class ContainerAllocator>
struct payload_fc_vfr_hud_status_
{
  typedef payload_fc_vfr_hud_status_<ContainerAllocator> Type;

  payload_fc_vfr_hud_status_()
    : header()
    , airspeed(0.0)
    , groundspeed(0.0)
    , heading(0.0)
    , throttle(0.0)
    , altmsl(0.0)
    , climb(0.0)  {
    }
  payload_fc_vfr_hud_status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , airspeed(0.0)
    , groundspeed(0.0)
    , heading(0.0)
    , throttle(0.0)
    , altmsl(0.0)
    , climb(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _airspeed_type;
  _airspeed_type airspeed;

   typedef float _groundspeed_type;
  _groundspeed_type groundspeed;

   typedef float _heading_type;
  _heading_type heading;

   typedef float _throttle_type;
  _throttle_type throttle;

   typedef float _altmsl_type;
  _altmsl_type altmsl;

   typedef float _climb_type;
  _climb_type climb;





  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> const> ConstPtr;

}; // struct payload_fc_vfr_hud_status_

typedef ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<std::allocator<void> > payload_fc_vfr_hud_status;

typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status > payload_fc_vfr_hud_statusPtr;
typedef boost::shared_ptr< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status const> payload_fc_vfr_hud_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.airspeed == rhs.airspeed &&
    lhs.groundspeed == rhs.groundspeed &&
    lhs.heading == rhs.heading &&
    lhs.throttle == rhs.throttle &&
    lhs.altmsl == rhs.altmsl &&
    lhs.climb == rhs.climb;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator1> & lhs, const ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kari_dronecop_rd_payload_mgmt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4edf75bc827a7c5c2cda21d9588377d4";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4edf75bc827a7c5cULL;
  static const uint64_t static_value2 = 0x2cda21d9588377d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kari_dronecop_rd_payload_mgmt/payload_fc_vfr_hud_status";
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Payload TmTc in ROS env., FC-VFR-Hud status\n"
"Header header\n"
"float32 airspeed\n"
"float32 groundspeed\n"
"float32 heading\n"
"float32 throttle\n"
"float32 altmsl\n"
"float32 climb\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.airspeed);
      stream.next(m.groundspeed);
      stream.next(m.heading);
      stream.next(m.throttle);
      stream.next(m.altmsl);
      stream.next(m.climb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct payload_fc_vfr_hud_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kari_dronecop_rd_payload_mgmt::payload_fc_vfr_hud_status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "airspeed: ";
    Printer<float>::stream(s, indent + "  ", v.airspeed);
    s << indent << "groundspeed: ";
    Printer<float>::stream(s, indent + "  ", v.groundspeed);
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
    s << indent << "throttle: ";
    Printer<float>::stream(s, indent + "  ", v.throttle);
    s << indent << "altmsl: ";
    Printer<float>::stream(s, indent + "  ", v.altmsl);
    s << indent << "climb: ";
    Printer<float>::stream(s, indent + "  ", v.climb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KARI_DRONECOP_RD_PAYLOAD_MGMT_MESSAGE_PAYLOAD_FC_VFR_HUD_STATUS_H
